# Generated by Django 5.2 on 2025-04-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_variation_variation_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('gender', 'gender'), ('color', 'color')], max_length=100),
        ),
    ]
